# Docker Compose for MCP Universal Bridge
# Run the MCP bridge in a container for easy deployment

version: '3.8'

services:
  # MCP Universal Bridge
  mcp-bridge:
    build:
      context: .
      dockerfile: bridge.Dockerfile
    container_name: mcp-universal-bridge
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      # Optional: Add authentication headers if needed
      # - MCP_AUTH_HEADER_Authorization=Bearer your-token
    # Expose stdio for MCP communication
    stdin_open: true
    tty: true
    # Optional: Mount config for persistent settings
    volumes:
      - ./bridge-config:/app/config:ro
    # Health check
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Bridge healthy')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Example: Bridge with specific domain discovery
  mcp-bridge-gmail:
    build:
      context: .
      dockerfile: bridge.Dockerfile
    container_name: mcp-bridge-gmail
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    command: ["tsx", "scripts/mcp-bridge.ts", "--domain", "gmail.com"]
    stdin_open: true
    tty: true
    profiles: ["examples"]

  # Example: Bridge with capability discovery
  mcp-bridge-email:
    build:
      context: .
      dockerfile: bridge.Dockerfile
    container_name: mcp-bridge-email
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    command: ["tsx", "scripts/mcp-bridge.ts", "--capability", "email"]
    stdin_open: true
    tty: true
    profiles: ["examples"]

# Optional: Create a network for bridge communication
networks:
  default:
    name: mcp-bridge-network
